name: URL自动替换

on:
  push:
    branches: [ main ]
    paths: [ 'XC.json' ]
  workflow_dispatch:  # 允许手动触发

# 授予工作流写入内容的权限
permissions:
  contents: write

jobs:
  replace-url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true  # 保持凭据以便后续push操作
          fetch-depth: 0
      
      - name: 设置Git用户信息
        run: |
          git config --local user.name "wwz09"
          git config --local user.email "wwz5124@gmail.com"
      
      - name: 执行URL替换
        run: |
          # 定义要替换的URL正则表达式模式和替换为的内容
          # 此正则表达式会匹配任何以raw.githubusercontent.com/yoursmile66/TVBox/refs/heads/main结尾的URL
          SEARCH_REGEX="https?://[^/]+/raw\.githubusercontent\.com/yoursmile66/TVBox/refs/heads/main"
          REPLACE_WITH="."
          
          # 备份原文件
          mkdir -p .backups
          cp XC.json .backups/XC.json.backup.$(date '+%Y%m%d%H%M%S')
          
          # 执行替换（使用-E选项启用扩展正则表达式）
          sed -i -E "s|$SEARCH_REGEX|$REPLACE_WITH|g" XC.json
          
          # 显示替换结果（使用-E选项启用扩展正则表达式）
          echo "替换前匹配数: $(grep -oE "$SEARCH_REGEX" .backups/XC.json.backup.* | wc -l)"
          echo "替换后匹配数: $(grep -oE "$SEARCH_REGEX" XC.json | wc -l)"
      
      - name: 提交更改
        run: |
          git add XC.json
          git commit -m "自动替换URL [skip ci]"
          # 使用GitHub Actions默认的GITHUB_TOKEN进行推送
          git push origin HEAD:main
        if: contains(github.event.head_commit.message, '[skip replace]') == false
