name: URL自动替换

on:
  push:
    branches: [ main ]
    paths: [ 'XC.json' ]
  workflow_dispatch:  # 允许手动触发

jobs:
  replace-url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Gitea兼容此action
        with:
          persist-credentials: false
          fetch-depth: 0
          token: ${{ secrets.PAT }}  # 在Gitea中设置同名密钥
      
      - name: 设置Git用户信息
        run: |
          git config --local user.name "wwz09 "
          git config --local user.email "wwz09@163.com"
      
      - name: 执行URL替换
        run: |
          SEARCH_REGEX="https?://[^/]+/raw\.githubusercontent\.com/yoursmile66/TVBox/refs/heads/main"
          REPLACE_WITH="."
          mkdir -p .backups
          cp XC.json .backups/XC.json.backup.$(date '+%Y%m%d%H%M%S')
          sed -i -E "s|$SEARCH_REGEX|$REPLACE_WITH|g" XC.json
          echo "替换前匹配数: $(grep -oE "$SEARCH_REGEX" .backups/XC.json.backup.* | wc -l)"
          echo "替换后匹配数: $(grep -oE "$SEARCH_REGEX" XC.json | wc -l)"
      
      - name: 提交更改
        run: |
          git add XC.json
          git commit -m "自动替换URL [skip ci]"
          git push https://$GITHUB_ACTOR:${{ secrets.PAT }}@your-gitea-instance.com/${{ gitea.repository }}.git HEAD:main
        if: contains(gitea.event.head_commit.message, '[skip replace]') == false
